import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { DiReact } from "react-icons/di"
import { SiNextdotjs } from "react-icons/si"
import { SiTailwindcss } from "react-icons/si"

export default function Home() {
	const cards = [
		{
			title: "useState",
			description: "useState is a Hook that lets you add React state to function components.",
			link: "/useState",
		},
		{
			title: "useEffect",
			description: "useEffect is a Hook that lets you perform side effects in function components.",
			link: "/useEffect",
		},
		{
			title: "useContext",
			description: "useContext is a Hook that lets you subscribe to React context without nesting.",
			link: "/useContext",
		},
	]

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-col h-fit items-center">
				<h1 className="text-7xl text-red-400 mt-20">Hi!</h1>
				<h2 className="text-6xl text-center text-white mt-4">
					I am using this to learn <span className="text-dark text-gray-950 font-medium">Next.js</span> + <span className="text-blue-400">React</span>.<br />
					Also, some <span className="text-blue-400">Tailwind</span>
				</h2>
				<div className="flex flex-row content-center gap-8 p-5 mt-4 text-8xl">
					<DiReact className="text-cyan-400" />
					<SiNextdotjs className="text-gray-950" />
					<SiTailwindcss className="text-blue-400" />
				</div>
				<hr className="h-1 w-4/6 mx-auto bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700 my-4"></hr>
				<div className="mt-lg grid gap-4 grid-cols-4 max-w-6xl">
					{cards.map((card, i) => (
						<Link href={card.link} key={i} className="rounded-2xl">
							<div className="flex flex-col gap-4 p-5 bg-gray-400 hover:outline-red-400 outline-gray-300 outline outline-4 rounded-2xl">
								<h3 className="text-2xl font-bold text-gray-800">{card.title}</h3>
								<p className="text-xl text-gray-700">{card.description}</p>
							</div>
						</Link>
					))}
				</div>
			</main>
		</>
	)
}
